{
 "title": "RecSys Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Запросы в секунду (по эндпоинтам)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(recsys_requests_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Латентность p95 (с)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(recsys_request_latency_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Доля попаданий в кэш",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "recsys_cache_hit_rate" }
   ]
  },
  {
   "title": "Выдач рекомендаций (всего)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "recsys_recommendations_total" }
   ]
  },
  {
   "title": "Доля cold start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(recsys_cold_start_total[5m]) / rate(recsys_recommendations_total[5m])",
     "legendFormat": "cold_start_rate"
    }
   ]
  }
 ]
}